services:
  ubs-data-agent:
    image: insightfinderinc/ubs-data-agent
    container_name: ubs
    volumes:
      - /insightfinder/logFileReplay-csv-ubs/config.yaml:/etc/config/ubs_data_agent.yaml
      - /insightfinder/logFileReplay-csv-ubs:/data
    # environment:
    #   - OPENBLAS_NUM_THREADS=1
    #   - NUMEXPR_NUM_THREADS=1
    #   - OMP_NUM_THREADS=1
    #   - MKL_NUM_THREADS=1
    
    