services:
  ubs-data-agent:
    image: insightfinderinc/ubs-data-agent
    container_name: ubs
    volumes:
      - /home/raja/repos/ubs-data-agent/ubs_data_agent/config/config_local.yaml:/etc/config/ubs_data_agent.yaml:ro
      - /tmp/ubs-data-agent-test:/data
    