mappings:
  efx_to_ibdl:
    paths:
      efx_data: "/data/processed_efx_*.csv"
      ibdl_data: "/data/IBDL_*.csv"
      output: /data/matches.json

    id_columns:
      - orderIntId
      - buySellIndicator
      - eventType
      - datetime
      - instrumentId
